spring:
  cloud:
    gateway:
      routes:
        - id: service-a
          uri: lb://service-a
          predicates:
            - Path=/serviceA/**

        - id: service-b
          uri: lb://service-b
          predicates:
            - Path=/serviceB/**
        - id: service-c
          uri: lb://service-c
          predicates:
            - Path=/serviceC/**     