spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: service-a
              uri: lb://service-a
              predicates:
                - Path=/serviceA/**
              filters:
                - StripPrefix=1
            - id: service-b
              uri: lb://service-b
              predicates:
                - Path=/serviceB/**
              filters:
                - StripPrefix=1
            - id: service-c
              uri: lb://service-c
              predicates:
                - Path=/serviceC/**
              filters:
                - StripPrefix=1